# 加密秘钥 生产环境中请修改为随机字符串，请勿外泄, 可使用命令生成
# $ cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 49;echo
SECRET_KEY: 'quBC9KRluSb1JORF5sv8Vjr6Bg7YFKMLne6HpejPhgi8QyFZP'

# DEBUG 模式 开启DEBUG后遇到错误时可以看到更多日志
DEBUG: true

# 日志等级
LOG_LEVEL: DEBUG

# 运行时绑定端口
HTTP_BIND_HOST: 0.0.0.0
HTTP_LISTEN_PORT: 8000

# TOKEN 过期时间
TOKEN_EXPIRE_DAYS: 7

# 开发环境
DevelopmentConfig:
  MYSQL_HOST: bj-cdb-o7k12jes.sql.tencentcdb.com
  MYSQL_PORT: 61840
  MYSQL_USER: work
  MYSQL_PWD: wiwide@312312
  MYSQL_DB: wise

  # Redis配置
  REDIS_HOST: 192.144.210.136
  REDIS_PORT: 3807
  REDIS_PWD: wiwide_redis_pass
  REDIS_DB: 1


# 测试环境
TestConfig:
  MYSQL_HOST: bj-cdb-o7k12jes.sql.tencentcdb.com
  MYSQL_PORT: 61840
  MYSQL_USER: work
  MYSQL_PWD: wiwide@312312
  MYSQL_DB: wise

  # Redis配置
  REDIS_HOST: 192.144.210.136
  REDIS_PORT: 3807
  REDIS_PWD: wiwide_redis_pass
  REDIS_DB: 1


# 生产环境
ProductionConfig:
  MYSQL_HOST: bj-cdb-o7k12jes.sql.tencentcdb.com
  MYSQL_PORT: 61840
  MYSQL_USER: work
  MYSQL_PWD: wiwide@312312
  MYSQL_DB: wise

  # Redis配置
  REDIS_HOST: 192.144.210.136
  REDIS_PORT: 3807
  REDIS_PWD: wiwide_redis_pass
  REDIS_DB: 1


CurrentConfig: ProductionConfig