# 加密秘钥 生产环境中请修改为随机字符串，请勿外泄, 可使用命令生成
# $ cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 49;echo
SECRET_KEY: 'quBC9KRluSb1JORF5sv8Vjr6Bg7YFKMLne6HpejPhgi8QyFZP'

# DEBUG 模式 开启DEBUG后遇到错误时可以看到更多日志
DEBUG: true

# 日志等级
LOG_LEVEL: DEBUG

# 运行时绑定端口
HTTP_BIND_HOST: 0.0.0.0
HTTP_LISTEN_PORT: 8000

# TOKEN 过期时间
TOKEN_EXPIRE_DAYS: 7

LDAP_SERVER_POOL: [ "ldap://10.10.x.x:389" ]  # proxy
ADMIN_DN: "CN=glpi,OU=server account,DC=xxx,DC=com"
ADMIN_PASSWORD: "xxxx"
SEARCH_BASE: "DC=xxxxx,DC=com"

# 开发环境
DevelopmentConfig:
  MYSQL_HOST:
  MYSQL_PORT:
  MYSQL_USER:
  MYSQL_PWD:
  MYSQL_DB:

  # Redis配置
  REDIS_HOST:
  REDIS_PORT:
  REDIS_PWD:
  REDIS_DB:


# 测试环境
TestConfig:
  MYSQL_HOST:
  MYSQL_PORT:
  MYSQL_USER:
  MYSQL_PWD:
  MYSQL_DB:

  # Redis配置
  REDIS_HOST:
  REDIS_PORT:
  REDIS_PWD:
  REDIS_DB:


# 生产环境
ProductionConfig:
  MYSQL_HOST:
  MYSQL_PORT:
  MYSQL_USER:
  MYSQL_PWD:
  MYSQL_DB:

  # Redis配置
  REDIS_HOST:
  REDIS_PORT:
  REDIS_PWD:
  REDIS_DB:


CurrentConfig: ProductionConfig