[tool.uv]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[project]
name = "ops-screenshot"
version = "0.1.0"
description = "Screenshot service"
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.116.1",
    "uvicorn==0.35.0",
    "playwright==1.57.0",
    "loguru>=0.7.3",
    "pyyaml>=6.0.3",
]
